Vincent/augmentation
talmolab/sleap-nn pull request #12
Opened 2023-07-27 20:25 UTC by alckasoc

2023-07-31 19:23 UTC, talmo requested changes

2023-07-31 19:23 UTC, talmo commented on environment.yml
> +  - torchdata
We stopped using `torchdata` as of #9.

2023-07-31 19:23 UTC, talmo commented on environment_cpu.yml
> +  - torchdata
We stopped using `torchdata` as of #9.

2023-07-31 19:23 UTC, talmo commented on environment_osx-arm64.yml
> +  - torchdata
We stopped using `torchdata` as of #9.

2023-07-31 19:23 UTC, talmo commented on pyproject.toml
> +    "torchdata",
We stopped using `torchdata` as of #9.

2023-07-31 19:23 UTC, talmo commented on sleap_nn/data/augmentation.py
> +from torchdata.datapipes.iter import IterDataPipe
We stopped using `torchdata` as of #9.

2023-07-31 19:23 UTC, talmo commented on sleap_nn/data/augmentation.py
> +        crop_p: float = 1.0,
Can we make random cropping optional?

2023-08-03 20:13 UTC, talmo requested changes

2023-08-03 20:13 UTC, talmo commented on tests/data/test_augmentation.py
> +        pass
Use [`pytest.raises`](https://docs.pytest.org/en/7.1.x/reference/reference.html#pytest.raises) to test for expected exceptions

2023-08-03 20:53 UTC, talmo approved these changes

2023-08-03 21:39 UTC, gitttt-1234 approved these changes

2023-08-04 01:36 UTC, merged