Adding ruff to ci.yml
talmolab/sleap-nn pull request #21
Opened 2023-09-20 09:31 UTC by alckasoc

2023-09-20 14:01 UTC, talmo commented
Are there supposed to be any outputs from ruff after linting @alckasoc? (Looking at the Action run logs.)

2023-09-20 14:02 UTC, talmo requested changes

2023-09-20 14:02 UTC, talmo commented on .github/workflows/ci.yml
> +    #     pydocstyle --convention=google sleap_nn/
Remove unused lines

2023-09-20 14:02 UTC, talmo commented on pyproject.toml
> +# [pydocstyle]
Remove unused lines

2023-09-21 17:15 UTC, alckasoc commented
I don't think ruff has a "No errors found." output like Black. There's a `--quiet` flag which suppresses all ruff outputs except for errors.

2023-09-21 19:20 UTC, talmo approved these changes

2023-09-26 22:07 UTC, merged